INSERT INTO "formaa"("formaaid", 
					 "brlistanepokretnosti", 
					  "mbropstine",
					 "opstina", 
					 "mbrkatastarskeopstine", 
					 "katastarskaopstina",
					 "datumazurnosti",
					"sluzba", 
					 "ulica", 
					 "brparcele", 
					 "podbrparcele", 
					 "povrsina", 
					 "brdela", 
					 "vrstazemljista",
					"kultura", 
					 "povrsinadela",
					 "vlasnik1", 
					 "vrstaprava1", 
					 "obliksvojine1", 
					 "udeo1", 
					"vlasnik2", 
					 "vrstaprava2", 
					 "obliksvojine2", 
					 "udeo2", 
					 "vremepopunjavanja", 
					 "greska", 
					 "redosled", 
					 "idkorisnik")
VALUES (nextval('formaA_seq'), 
		'12684', 
		'80152',
		'Zrenjanin',
	   '805742',
	   'Zrenjanin I',
	   '23.06.2021.',
	   'Zrenjanin',
	   'Begejski red',
	   6371,
	   2,
	   428,
	   1,
	   'Gradsko gradjevinsko zemljiste',
	   'Zemljiste pod zgradom i drugim objektom',
		196,
	   'Gladic (Vlada) Mila',
	   'Pravo koriscenja',
	   'Privatna',
	  '3/10',
		'Gladic (Miroslav) Dragan',
	   'Pravo koriscenja',
	   'Privatna',
	   '3/10',
		null,
		0,
		null,
		null
	   );

INSERT INTO "formab"("formabid", 
					 "brlistanepokretnosti", 
					 "mbropstine",
					 "opstina", 
					 "mbrkatastarskeopstine", 
					 "katastarskaopstina",
					 "datumazurnosti",
					"sluzba", 
					 "ulica", 
					 "brparcele", 
					 "podbrparcele", 
					 "povrsina", 
					 "brdela", 
					 "vrstazemljista",
					"kultura", 
					 "povrsinadela",
					 "vlasnik1", 
					 "vrstaprava1", 
					 "obliksvojine1", 
					 "udeo1", 
					"vlasnik2", 
					 "vrstaprava2", 
					 "obliksvojine2", 
					 "udeo2", 
					 "vremepopunjavanja", 
					 "greska", 
					 "redosled", 
					 "idkorisnik")
VALUES (nextval('formaB_seq'), 
		'4654', 
			'80152',
		'Zrenjanin',
	   '805742',
	   'Zrenjanin I',
	   '23.06.2021.',
	   'Zrenjanin',
	   'Nikole Pasica',
	   6736,
	   2,
	   616,
	   1,
	   'Gradsko gradjevinsko zemljiste',
	   'Zemljiste pod zgradom i drugim objektom',
		210,
	   'Petrovacki Ljiljana',
	   'Svojina',
	   'Privatna',
	   '1/2',
		'Petrovacki (Petar) Svetozar',
	   'Svojina',
	   'Privatna',
	   '1/2',
		null,
		0,
		null,
		null
	   );
	

insert into starosnagrupa
values (1,1,20), (2,21,30), (3,31,40), (4,41,50), (5,51,60), (6,60,99)